export const data = [
  {
    id: 1,
    name: "Kannada Alphabet Learning for Beginners",
    image: "https://i.imgur.com/GSPMzLk.jpg",
    price: "350.00",
    brand: "UpToSchoolWorksheets",
    inStock: true,
    fastDelivery: false,
    ratings: 4.5,
    level: "beginner",
  },
  {
    id: 2,
    name: "Kannada Writing Practice (Pack of 2)",
    image: "https://i.imgur.com/RrOiKHx.jpg",
    price: "510.00",
    brand: "InIkao Foundations",
    inStock: true,
    fastDelivery: true,
    ratings: 3.9,
    level: "beginner",
  },
  {
    id: 3,
    name: "Writing Alphabets Practice Book Set of 5",
    image: "https://i.imgur.com/ssZkxod.jpg",
    price: "799.00",
    brand: "Rajkumar (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.3,
    level: "beginner",
  },
  {
    id: 4,
    name: "Kannada Letters Practice for Beginners",
    image: "https://i.imgur.com/xAiS7XI.jpg",
    price: "880.00",
    brand: "Heemansshu (Author)",
    inStock: false,
    fastDelivery: false,
    ratings: 2.2,
    level: "beginner",
  },
  {
    id: 5,
    name: "Introduction Of Kannada Letters",
    image: "https://i.imgur.com/IG2aaKm.jpg",
    price: "150.00",
    brand: "Heemansshu (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 2.0,
    level: "beginner",
  },
  {
    id: 6,
    name: "Non Kannadiga To Naanu Kannadiga",
    image: "https://i.imgur.com/b6NzQ1J.jpg",
    price: "99.00",
    brand: "Sridevi Shetty (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 3.9,
    level: "intermediate",
  },
  {
    id: 7,
    name: "Kannada Characters Practice",
    image: "https://i.imgur.com/glxNpMT.jpg",
    price: "99.00",
    brand: "In House",
    inStock: false,
    fastDelivery: false,
    ratings: 2.9,
    level: "intermediate",
  },
  {
    id: 8,
    name: "Kannada Reading for Learners (Level 1)",
    image: "https://i.imgur.com/fGK6s9Q.jpg",
    price: "665.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.1,
    level: "intermediate",
  },
  {
    id: 9,
    name: "Kannada Reading for Learners (Level 2)",
    image: "https://i.imgur.com/Xpq9O5n.jpg",
    price: "270.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.4,
    level: "intermediate",
  },
  {
    id: 10,
    name: "Kannada Reading for Learners (Level 3)",
    image: "https://i.imgur.com/misIDF2.jpg",
    price: "375.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.0,
    level: "intermediate",
  },
  {
    id: 11,
    name: "Kannada Reading for Learners (Level 4)",
    image: "https://i.imgur.com/W6O6AgC.jpg",
    price: "480.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 3.1,
    level: "intermediate",
  },
  {
    id: 12,
    name: "Kannada Reading for Learners (Level 5)",
    image: "https://i.imgur.com/OeX1hbS.jpg",
    price: "685.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 3.4,
    level: "intermediate",
  },
  {
    id: 13,
    name: "Kannada Glossary 1",
    image: "https://i.imgur.com/h4VL92T.jpg",
    price: "775.00",
    brand: "Vasantha Prakaashana (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 1.4,
    level: "beginner",
  },
  {
    id: 14,
    name: "Kannada Grammar and Composition 2",
    image: "https://i.imgur.com/bFCpV4a.jpg",
    price: "980.00",
    brand: "N GopalKrishna Udupa (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 4.9,
    level: "advanced",
  },
  {
    id: 15,
    name: "Kannada Standard Grammar",
    image: "https://i.imgur.com/IcG9zlP.jpg",
    price: "890.00",
    brand: "H.S.K. VISVESHWARAIAH (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 2.9,
    level: "advanced",
  },
  {
    id: 16,
    name: "Kannada Pocket Dictionary",
    image: "https://i.imgur.com/IbzSOi4.jpg",
    price: "400.00",
    brand: "Parishkrutha",
    inStock: false,
    fastDelivery: true,
    ratings: 2.9,
    level: "beginner",
  },
  {
    id: 17,
    name: "Kannada Grammar and Composition 1",
    image: "https://i.imgur.com/7D32hIH.jpg",
    price: "480.00",
    brand: "N GopalKrishna Udupa (Author)",
    inStock: false,
    fastDelivery: true,
    ratings: 4.7,
    level: "advanced",
  },
  {
    id: 18,
    name: "Kannada Consonants",
    image: "https://i.imgur.com/rTq8VZf.jpg",
    price: "65.00",
    brand: "Various Authors",
    inStock: true,
    fastDelivery: false,
    ratings: 2.7,
    level: "beginner",
  },
  {
    id: 19,
    name: "Modern Kannada Grammar",
    image: "https://i.imgur.com/CGihexz.jpg",
    price: "285.00",
    brand: "Professor S N Sridhar (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.6,
    level: "intermediate",
  },
  {
    id: 20,
    name: "Kannada Grammar and Composition",
    image: "https://i.imgur.com/AoWEggq.jpg",
    price: "179.00",
    brand: "N GopalKrishna Udupa (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.9,
    level: "professional",
  },
];
