export const data = [
  {
    id: 1,
    name: "Kannada Glossary 1",
    image: "https://images-na.ssl-images-amazon.com/images/I/61pWUG8tdxL.jpg",
    price: "775.00",
    brand: "Vasantha Prakaashana (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 4.5,
    level: "beginner",
  },
  {
    id: 2,
    name: "Kannada Reading for Learners (Level 1)",
    image: "https://images-na.ssl-images-amazon.com/images/I/91HKZ35QwpL.jpg",
    price: "665.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.1,
    level: "intermediate",
  },
  {
    id: 3,
    name: "Writing Alphabets Practice Book Set of 5",
    image: "https://images-na.ssl-images-amazon.com/images/I/919ojS-QBRL.jpg",
    price: "799.00",
    brand: "Rajkumar (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.3,
    level: "beginner",
  },
  {
    id: 4,
    name: "Kannada Characters Practice",
    image: "https://images-na.ssl-images-amazon.com/images/I/8143yAqJw+L.jpg",
    price: "99.00",
    brand: "In House",
    inStock: false,
    fastDelivery: false,
    ratings: 2.9,
    level: "intermediate",
  },
  {
    id: 5,
    name: "Introduction Of Kannada Letters",
    image: "https://images-na.ssl-images-amazon.com/images/I/916WO6df+IL.jpg",
    price: "150.00",
    brand: "Heemansshu (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 2.0,
    level: "beginner",
  },
  {
    id: 6,
    name: "Non Kannadiga To Naanu Kannadiga",
    image: "https://images-na.ssl-images-amazon.com/images/I/81TLR-IjTZL.jpg",
    price: "99.00",
    brand: "Sridevi Shetty (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 3.9,
    level: "intermediate",
  },
  {
    id: 7,
    name: "Kannada Letters Practice for Beginners",
    image: "https://images-na.ssl-images-amazon.com/images/I/91I61MkqzeS.jpg",
    price: "880.00",
    brand: "Heemansshu (Author)",
    inStock: false,
    fastDelivery: false,
    ratings: 2.2,
    level: "beginner",
  },
  {
    id: 8,
    name: "Kannada Grammar and Composition 2",
    image: "https://images-na.ssl-images-amazon.com/images/I/51LTjXLTN6S.jpg",
    price: "980.00",
    brand: "N GopalKrishna Udupa (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 4.9,
    level: "advanced",
  },
  {
    id: 9,
    name: "Kannada Reading for Learners (Level 2)",
    image: "https://images-na.ssl-images-amazon.com/images/I/91N2zi0KugL.jpg",
    price: "270.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.4,
    level: "intermediate",
  },
  {
    id: 10,
    name: "Kannada Standard Grammar",
    image: "https://images-na.ssl-images-amazon.com/images/I/41t6dphGFpL.jpg",
    price: "890.00",
    brand: "H.S.K. VISVESHWARAIAH (Author)",
    inStock: true,
    fastDelivery: true,
    ratings: 2.9,
    level: "advanced",
  },
  {
    id: 11,
    name: "Kannada Reading for Learners (Level 4)",
    image: "https://images-na.ssl-images-amazon.com/images/I/91sZ+ztV9rL.jpg",
    price: "480.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 3.1,
    level: "intermediate",
  },
  {
    id: 12,
    name: "Kannada Alphabet Learning for Beginners",
    image: "https://images-na.ssl-images-amazon.com/images/I/81Cn9Bz-WtL.jpg",
    price: "350.00",
    brand: "UpToSchoolWorksheets",
    inStock: true,
    fastDelivery: false,
    ratings: 1.2,
    level: "beginner",
  },
  {
    id: 13,
    name: "Kannada Reading for Learners (Level 5)",
    image: "https://images-na.ssl-images-amazon.com/images/I/71L3IsM6n-L.jpg",
    price: "685.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 3.4,
    level: "intermediate",
  },
  {
    id: 14,
    name: "Kannada Writing Practice (Pack of 2)",
    image: "https://images-na.ssl-images-amazon.com/images/I/81nhT4dlPZL.jpg",
    price: "510.00",
    brand: "InIkao Foundations",
    inStock: true,
    fastDelivery: true,
    ratings: 3.9,
    level: "beginner",
  },
  {
    id: 15,
    name: "Kannada Reading for Learners (Level 3)",
    image: "https://images-na.ssl-images-amazon.com/images/I/91Ea5ztXRUL.jpg",
    price: "375.00",
    brand: "S.L.Srinivasamurthy (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.0,
    level: "intermediate",
  },
  {
    id: 16,
    name: "Kannada Pocket Dictionary",
    image: "https://images-na.ssl-images-amazon.com/images/I/81L+lsvkWuL.jpg",
    price: "400.00",
    brand: "Parishkrutha",
    inStock: false,
    fastDelivery: true,
    ratings: 2.9,
    level: "beginner",
  },
  {
    id: 17,
    name: "Kannada Grammar and Composition 1",
    image: "https://images-na.ssl-images-amazon.com/images/I/91Mvmmp8TSL.jpg",
    price: "480.00",
    brand: "N GopalKrishna Udupa (Author)",
    inStock: false,
    fastDelivery: true,
    ratings: 4.7,
    level: "advanced",
  },
  {
    id: 18,
    name: "Kannada Consonants",
    image: "https://images-na.ssl-images-amazon.com/images/I/41ZZcBXqjcL.jpg",
    price: "65.00",
    brand: "Various Authors",
    inStock: true,
    fastDelivery: false,
    ratings: 2.7,
    level: "beginner",
  },
  {
    id: 19,
    name: "Modern Kannada Grammar",
    image: "https://images-na.ssl-images-amazon.com/images/I/510JvNtSBmL.jpg",
    price: "285.00",
    brand: "Professor S N Sridhar (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.6,
    level: "intermediate",
  },
  {
    id: 20,
    name: "Kannada Grammar and Composition",
    image: "https://images-na.ssl-images-amazon.com/images/I/41dyA5IcBKL.jpg",
    price: "179.00",
    brand: "N GopalKrishna Udupa (Author)",
    inStock: true,
    fastDelivery: false,
    ratings: 4.9,
    level: "advanced",
  },
];
